sudo: false
dist: trusty
language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
before_script:
- chmod +x scripts/docs
script:
- npm run test:coverage -- --runInBand
- npm run lint
after_success:
- scripts/docs
- npx codecov --file=./coverage/lcov.info
before_deploy:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: junminliu@gmail.com
  api_key:
    secure: HUZ9iQCzdcDBbkmvT4kmZbhYzc4KtvijP7PTt33MJ2eIFXpNK+E6ynO/8/UGR7Re6aersR1nm5LOiaLqwuoCvMxwqbVGvOd7dRjlKQG4twKFvze3fpvEpJWP+ZK1y4VK2QTyD2LjS7ocXX2Yi7PindNjbt4N5PMVUFBAIlp2GoeIXRz3qKieVuLMnV2Y/SPzIVufM3IGutP2WtEFnf++e3VVAkQaL6DykyYmHdsCBzOXQ7I7axeQqYOh9DjlxSeLq1G6ntLp4IHwVGUXeEhvbndSa1P70Fa70L7O+80fPBuvn/B077j0jceSRCbVzNG2pgS0MstM4loUq2nMjxV7OaLPe8Zf4zmGUiALkhS4YFaylPRCLfnY/ekXht5dJrTjPQACsbs74XOyOdWl8KNtKS3hj6uiftLnAMOf/2Tb5UUrcvFxEQS1+aZjMVTWk1c528FUUhVbDPskq5GqUSSxeUhlQRb+oMIX6Vins0YAM5GGcxJ/COTpRWfM82/8Cy6myw7qTo8u7MnXql5jSmDaDtWFnysLzkLVrKxlMDuXuQpxTRP/vL/4YCgxO0OJb2XBgvglJ0UKcDpDBQIvLtnFpSmdvjlwi7TUtNLEjJ2WsR86cST7uloR+mYZWM3sslAhf+aSLT2ShzLMG5N11cfQeEBRPcuEM4qt8rtfjeGUOMA=
  on:
    tags: true
    all_branches: true
    repo: video-react/video-react
